"""vmalert recording rules for the 1-minute rollups, generated from the signal registry (design 5.5).

    ting-exporter rules > deploy/vmalert/ting-rollups.yml

Every rollup of every Signal becomes one rule `ting:<metric>:<agg>_1m`. An
evaluation at the aligned minute T covers (T-60 s, T] and is stamped T.
`eval_delay: 60s` keeps the evaluation a minute behind real time, so samples
that arrive up to ~13 s late (buffered delivery) plus a 5 s push batch are in
VictoriaMetrics before their minute is computed. The rollup repair (repair.py)
evaluates the same expressions for minutes vmalert missed.
"""

from __future__ import annotations

from collections.abc import Iterator
from decimal import Decimal

from .signals import REGISTRY, ROLLUP_WINDOW, Rollup, Signal

GROUP = "ting_rollup_1m"
EVAL_DELAY = "60s"

HEADER = """\
# Generated by `ting-exporter rules` from src/ting_exporter/signals.py. Do not edit by hand:
# tests/test_signals.py fails when this file and the signal registry disagree.
#
# Evaluated at each aligned minute T with window (T-60s, T], stamped T. A minute without
# raw samples gets no rollup point. Minutes vmalert missed (VictoriaMetrics down, raw data
# that arrived late) are filled by the exporter's rollup repair from the same expressions.
"""


def _step(value: float) -> str:
    return format(Decimal(repr(value)).normalize(), "f")


def expression(signal: Signal, rollup: Rollup, selector: str = "") -> str:
    """The rule's MetricsQL; `selector` (e.g. 'serial="X"') narrows it to one series for the repair."""
    inner = f"{rollup.agg}_over_time({signal.metric}{{{selector}}}[{ROLLUP_WINDOW}])" if selector else \
        f"{rollup.agg}_over_time({signal.metric}[{ROLLUP_WINDOW}])"
    return f"round({inner}, {_step(rollup.round_to)})" if rollup.round_to is not None else inner


def every_rule(registry: tuple[Signal, ...] = REGISTRY) -> Iterator[tuple[Signal, Rollup]]:
    for signal in registry:
        for rollup in signal.rollups:
            yield signal, rollup


def render(registry: tuple[Signal, ...] = REGISTRY) -> str:
    lines = [
        HEADER.rstrip("\n"),
        "groups:",
        f"  - name: {GROUP}",
        f"    interval: {ROLLUP_WINDOW}",
        f"    eval_delay: {EVAL_DELAY}",
        "    rules:",
    ]
    for signal in registry:
        if not signal.rollups:
            continue
        lines.append(f"      # {signal.key}: {signal.metric} ({signal.unit}), stored {signal.storage}")
        for rollup in signal.rollups:
            lines.append(f"      - record: {signal.record_name(rollup)}")
            lines.append(f"        expr: {expression(signal, rollup)}")
    return "\n".join(lines) + "\n"
